#给项目加一个路径  此时在浏览器器上就要输出localhost:8080/community/hello
server:
  servlet:
    context-path: /community

#关闭Thymeleaf的缓存
spring:
  thymeleaf:
    cache: false
  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    password: root
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #连接池最大连接数
      maximum-pool-size: 15
      minimum-idle: 5
      #超时时间
      idle-timeout: 30000
  #配置email
  mail:
    host: smtp.qq.com
    username: 1124503837@qq.com
    password: gcksitkpvzymhgdd
    protocol: smtps
    properties:
      mail:
        smtl:
          ssl:
            enable: true
#redisProperties
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 980502xr.
    database: 11
  #kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
#ElasticsearchProperties
  data:
    elasticsearch:
      #集群的名字
#      cluster-name: newCoder
#      #集群的节点 9200端口为http访问的端口 9300端口为tcp端口  应用服务通过用tcp端口
#      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  #TaskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5 #核心线程数
        max-size: 15 #最大线程数
        queue-capacity: 100 #当已经达到最大线程数还不够用，就存在队列中，这个队列的容量为100
    #TaskSchedulingProperties
    scheduling:
      pool:
        size: 5






#mybatis配置
mybatis:
  #配置映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置实体类别名
  type-aliases-package: com.rxue.entity
  configuration:
    #启用自动生成主键
    use-generated-keys: true
    #让下划线的命名方式和驼峰命名方式自动匹配
    #header_url  headerUrl
    map-underscore-to-camel-case: true
#    #启动日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志级别
logging:
  level:
    com.rxue: debug
##日志记录的路径和文件名
#  file:
#    path: 'E:/Java/workspace_idea/newCoder'
#    name: 'community.log'


#newCoder 自定义内容  域名 激活路径  头像上传路径
newCoder:
  path:
    domain: http://localhost:8080
    activation: /activation/
    upload: E:/Java/workspace_idea/newCoder/data/upload/


#wk
wk:
  image:
    command: E:/wkhtmltopdf/bin/wkhtmltoimage
    storage: E:/Java/workspace_idea/newCoder/wk-images

#caffeine
caffeine:
  posts:
    max-size: 15 #最大存15个
    expire-seconds: 180 #三分钟过期

#actuator
management:
  endpoints:
    web:
      exposure:
        #所有的端口都暴露  在关闭几个端口
        include: '*'
        exclude: caches
